# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

# Overwrite or add rules to create your own house style
Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/TrailingWhitespace:
  Enabled: true

Layout/TrailingEmptyLines:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true