inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'  # Temporarily exclude specs

Rails:
  Enabled: true

RSpec:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'