services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coin_guru_api_test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/coin_guru_api_test
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["bin/rails", "test"]

volumes:
  pg_data:
