FROM ruby:3.3.0-slim

# Install dependencies
RUN apt-get update -qq && apt-get install --no-install-recommends -y \
    curl \
    gnupg \
    libjemalloc2 \
    libvips \
    libpq-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Add PostgreSQL repository and install the correct version of the PostgreSQL client
RUN echo "deb http://apt.postgresql.org/pub/repos/apt $(grep -oP 'VERSION_CODENAME=\K\w+' /etc/os-release)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list && \
    curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && \
    apt-get update -qq && \
    apt-get install --no-install-recommends -y postgresql-client-17 && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /coin_guru_api

# Print environment variables for debugging
RUN printenv

# Copy Gemfile and install gems
COPY Gemfile Gemfile.lock ./
RUN gem update --system 3.3.22 && \
    gem install bundler -v 2.6.3 && \
    bundle install --jobs=4 --retry=3

# Copy the rest of the application code
COPY . .

# Ensure the entrypoint script is executable
RUN chmod +x bin/docker-entrypoint

# Set environment variables
ENV RAILS_ENV=test

# Create .env file from build arguments
ARG POSTGRES_USER
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB_TEST
ARG POSTGRES_PORT
ARG RAILS_MASTER_KEY

RUN echo "POSTGRES_USER=${POSTGRES_USER}" >> .env && \
    echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env && \
    echo "POSTGRES_DB_TEST=${POSTGRES_DB_TEST}" >> .env && \
    echo "POSTGRES_PORT=${POSTGRES_PORT}" >> .env && \
    echo "RAILS_MASTER_KEY=${RAILS_MASTER_KEY}" >> .env

# Run the entrypoint script
ENTRYPOINT ["bin/docker-entrypoint"]

# Run the Rails server CI
CMD ["bin/rails", "server", "-b", "0.0.0.0"]