services:
  db:
    image: postgres:17
    restart: always
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 5s
      timeout: 10s
      retries: 15
    networks:
      - app-network

  web:
    build:
      context: .
      target: test
    restart: unless-stopped
    environment:
      RAILS_ENV: test
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      COIN_GECKO_API_URL: ${COIN_GECKO_API_URL}
      COIN_GECKO_API_TOKEN: ${COIN_GECKO_API_TOKEN}
      RAILS_MAX_THREADS: 2
      RUBY_GC_MALLOC_LIMIT: 100000000
      RUBY_GC_OLDMALLOC_LIMIT: 20000000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/up || exit 1"]
      interval: 10s
      timeout: 15s
      retries: 10
    networks:
      - app-network

volumes:
  postgres_data_test:

networks:
  app-network: