services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}          
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_DEV}               
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"] 
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    build:
      context: .
      target: development
    volumes:
      - .:/coin_guru_api
      - bundle:/usr/local/bundle
    env_file:
      - .env.dev
    environment:
      POSTGRES_HOST: db                         
      POSTGRES_PORT: 5432                       
      POSTGRES_USER: ${POSTGRES_USER}           
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}   
      POSTGRES_DB: ${POSTGRES_DB_DEV}           
      RAILS_ENV: development
      BUNDLE_PATH: "/usr/local/bundle"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-network
    tmpfs:
      - /coin_guru_api/tmp

volumes:
  postgres_data: {}
  bundle: {}

networks:
  app-network:
    driver: bridge