services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  web:
    build:
      context: .
      target: development
    volumes:
      - .:/coin_guru_api
      - bundle:/usr/local/bundle
    env_file:
      - .env.dev
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      RAILS_ENV: development
      BUNDLE_PATH: "/usr/local/bundle"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - app-network
    tmpfs:
      - /coin_guru_api/tmp

volumes:
  postgres_data: {}
  bundle: {}

networks:
  app-network:  # Explicitly define the network
    driver: bridge  # Use the default bridge driver