services:
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coin_guru_api_test

  web:
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/coin_guru_api_test
      RAILS_ENV: test
      RAILS_MAX_THREADS: 2
      RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR: 1.3
      RUBY_GC_MALLOC_LIMIT: 90000000
      RUBY_GC_OLDMALLOC_LIMIT: 16000000
      WEB_TIMEOUT: 60