default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB_DEV') { 'coin_guru_api_development' } %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB') { 'coin_guru_api_test' } %>
  host: db
  port: 5432
  connect_timeout: 10
  prepared_statements: false
  variables:
    statement_timeout: 5000

production:
  <<: *default
  database: coin_guru_api_production