# name: CI

# on:
#   pull_request:
#   push:
#     branches: [ main ]

# jobs:
#   scan_ruby:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version
#           bundler-cache: true

#       - name: Update RubyGems to the required version
#         run: gem update --system 3.3.22

#       - name: Install Dependencies
#         run: |
#           bundle install --jobs 4 --retry 3
#           bundle binstubs railties --force

#       - name: Scan for security vulnerabilities
#         run: bin/brakeman --no-pager

#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: .ruby-version
#           bundler-cache: true
#       - run: bundle exec rubocop -f github --only-recognized-file-types

#       - name: Update RubyGems to the required version
#         run: gem update --system 3.3.22

#       - name: Install Dependencies
#         run: |
#           bundle install --jobs 4 --retry 3
#           bundle binstubs railties --force

#       - name: Lint code for style consistency
#         run: bin/rubocop -f github

#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:17.4
#         env:
#           POSTGRES_USER: postgres
#           POSTGRES_PASSWORD: postgres
#           POSTGRES_DB: coin_guru_api_test
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     steps:
#     - uses: actions/checkout@v4

#     - name: Set up Ruby
#       uses: ruby/setup-ruby@v1
#       with:
#         ruby-version: 3.2.2
#         bundler-cache: true

#     - name: Install PostgreSQL Client
#       run: |
#         sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
#         wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#         sudo apt-get update
#         sudo apt-get install postgresql-client-17

#     - name: Database setup
#       env:
#         RAILS_ENV: test
#         POSTGRES_HOST: localhost
#         POSTGRES_USER: postgres
#         POSTGRES_PASSWORD: postgres
#         POSTGRES_DB: coin_guru_api_test
#       run: |
#         bundle install
#         bundle exec rails db:prepare

#     - name: Run tests
#       env:
#         RAILS_ENV: test
#         POSTGRES_HOST: localhost
#         POSTGRES_USER: postgres
#         POSTGRES_PASSWORD: postgres
#         POSTGRES_DB: coin_guru_api_test
#       run: bundle exec rspec