name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Update RubyGems to the required version
        run: gem update --system 3.3.22

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3
          bundle binstubs railties --force

      - name: Scan for security vulnerabilities
        run: bin/brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Update RubyGems to the required version
        run: gem update --system 3.3.22

      - name: Install Dependencies
        run: |
          bundle install --jobs 4 --retry 3
          bundle binstubs railties --force

      - name: Lint code for style consistency
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      COIN_GECKO_API_URL: ${{ secrets.COIN_GECKO_API_URL }}
      COIN_GECKO_API_TOKEN: ${{ secrets.COIN_GECKO_API_TOKEN }}
      DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ secrets.POSTGRES_DB }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            docker-

      - name: Increase Swap Memory
        run: |
          sudo dd if=/dev/zero of=/swapfile bs=1G count=4
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo sysctl vm.swappiness=25
          free -h

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.test.yml build --no-cache
          docker-compose -f docker-compose.test.yml up -d
          docker-compose -f docker-compose.test.yml ps

      - name: Database readiness checks
        timeout-minutes: 5
        run: |
          echo "Waiting for database..."
          docker-compose -f docker-compose.test.yml exec -T db \
            bash -c "until pg_isready -U $POSTGRES_USER -d $POSTGRES_DB; do sleep 2; done"
          
          echo "Database connection test:"
          docker-compose -f docker-compose.test.yml exec -T db \
            psql -U $POSTGRES_USER -d $POSTGRES_DB -c '\conninfo'

      - name: Database setup with retries
        run: |
          function rails_db() {
            docker-compose -f docker-compose.test.yml exec -T web bundle exec rails "$@"
          }

          for i in {1..3}; do
            rails_db db:create && rails_db db:migrate && rails_db db:test:prepare && break
            echo "Attempt $i failed, retrying..."
            sleep 5
          done

          rails_db db:version

      - name: Run test suite
        run: |
          docker-compose -f docker-compose.test.yml exec -T web \
            bundle exec rspec --format documentation

      - name: Cleanup resources
        if: always()
        run: |
          docker-compose -f docker-compose.test.yml down -v
          docker system prune -a --force